### ISSUE TITLE
symmpa aliases for each robot are not created

### ISSUE THREAD

**Issue by pvn802** [sympa-community/sympa-contribs#6]
Hello,

The sympatoldap.pl script do not create the aliases that are used for all the lists of a robot:
- sympa
- listmaster
- sympa-request
- sympa-owner
You can see them in the postfix sympa.aliases file

There is also the bounce+* alias that means that return addresses are generated dynamically. So I think that VERP feature cannot be used with this script

Regards

P

**Comment by racke** [comment]
Which script are you referring to?

**Comment by pvn802** [comment]
sympatoldap.pl. I already edited my first post

**Comment by tvo6** [comment]
Good point…
I don't have any test infrastructure anymore, but you may test something like (in sympatoldap.pl):
```
@@ -456,6 +456,12 @@ sub get_lists_for_robot {
         close $listconf;
         say Dumper($lists->{$r}->{'lists'}->{$l}) if ($debug >= 6);
     }
+    $lists->{$r}->{'lists'}->{'sympa'} = {
+        'subject'    => 'Robot $r listmasters',
+        'status'     => 'open',
+        'visibility' => 'conceal',
+        'owners'     => $lists>{$r}->{'listmaster'},
+    };
 }
 
 sub get_listinfo_from_ldap {
```

**Comment by pvn802** [comment]
Hello,

Yes, this does the job but I preferred to add this at the beginning of the get_lists_for_robot function

There is just one typo, you should have
            'owners'     => [ $lists->{$r}->{'listmaster'} ] ,

But this reveals another issue, the DN of the records does not contains the robot name so if you have 2 robots it will fail for this sympa pseudo list
